CREATE TABLE COMPANY_LOCATION (
    COMPANY_LOCATION_ID bigint AUTO_INCREMENT primary key,
    LOCATION varchar
);

CREATE TABLE COMPANY_TYPE (
    COMPANY_TYPE_ID bigint AUTO_INCREMENT primary key,
    TYPE varchar
);

CREATE TABLE MEMBER (
    ID bigint AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(255),
    PASSWORD varchar(255),
    SEX varchar(255),
    COMPANY_NAME varchar(255),
    COMPANY_LOCATION_ID bigint,
    COMPANY_TYPE_ID bigint
);

insert into COMPANY_LOCATION(LOCATION) VALUES('서울');
insert into COMPANY_LOCATION(LOCATION) VALUES('경기');
insert into COMPANY_LOCATION(LOCATION) VALUES('부산');
insert into COMPANY_LOCATION(LOCATION) VALUES('광주');
insert into COMPANY_LOCATION(LOCATION) VALUES('울산');
insert into COMPANY_LOCATION(LOCATION) VALUES('강원도');
insert into COMPANY_LOCATION(LOCATION) VALUES('전라도');
insert into COMPANY_LOCATION(LOCATION) VALUES('경상도');
insert into COMPANY_LOCATION(LOCATION) VALUES('제주도');
insert into COMPANY_LOCATION(LOCATION) VALUES('인천');


insert into COMPANY_TYPE(TYPE) VALUES('정보통신');
insert into COMPANY_TYPE(TYPE) VALUES('도소매');
insert into COMPANY_TYPE(TYPE) VALUES('전자공학');
insert into COMPANY_TYPE(TYPE) VALUES('의료');
insert into COMPANY_TYPE(TYPE) VALUES('토목');
insert into COMPANY_TYPE(TYPE) VALUES('건축');
insert into COMPANY_TYPE(TYPE) VALUES('광고');

insert into MEMBER(NAME, PASSWORD, SEX, COMPANY_NAME, COMPANY_TYPE_ID, COMPANY_LOCATION_ID) values('홍길동', 'hh1234', 'w', 'bgmCompany', 1, 1);
